### ISSUE TITLE
geckodriver is not installing in my corporate firewall

### ISSUE THREAD

**Issue by id4automation** [john-doherty/selenium-cucumber-js#73] opened 2018-08-03 16:02 UTC
I am able to download electron, chromedriver and phatonjs . but after that when it tries to download geckodriver it is failing. Need some help on how to fix this.

> > electron@1.8.7 postinstall C:\Users\A632694\testJS\node_modules\electron
> > node install.js
> 
> 
> > geckodriver@1.1.2 postinstall C:\Users\A632694\testJS\node_modules\geckodriver
> > node index.js
> 
> Downloading geckodriver...
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> RequestError: getaddrinfo ENOTFOUND github.com github.com:443
>     at ClientRequest.<anonymous> (C:\Users\A632694\testJS\node_modules\got\index.js:69:21)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at TLSSocket.socketErrorListener (_http_client.js:387:9)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> npm WARN testJS@1.0.0 No description
> npm WARN testJS@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! geckodriver@1.1.2 postinstall: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the geckodriver@1.1.2 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mivtachyahu** [comment] 2018-08-17 11:00
I found this same issue today. This is I think because the downloader that geckodriver at version 1.1.2 uses  doesn't read in HTTP_PROXY / HTTPS_PROXY environment variables. It is only at the most recent version (1.12.2) that these variables get read in (see: https://github.com/vladikoff/node-geckodriver/issues/21).

**Comment by john-doherty** [comment] 2018-08-18 14:36
Please can someone resolve this and issue a pull request?

**Comment by mivtachyahu** [comment] 2018-08-20 11:51
Raised: https://github.com/john-doherty/selenium-cucumber-js/pull/74

**Comment by anavaneethagopalan** [comment] 2018-08-21 21:52
Thansk and much appreciated.

**Comment by john-doherty** [comment] 2018-08-22 11:25
#74 is now merged and push to npm, please can you grab the latest and confirm this issue is resolved?

**Comment by mivtachyahu** [comment] 2018-08-22 11:42
I can confirm that I managed to install it behind a proxy & firewall with the HTTP_PROXY and HTTPS_PROXY environment variables set. @id4automation ?

**Comment by john-doherty** [comment] 2018-08-23 18:27
I'm closing this. Thanks for your help

**Closed by john-doherty** 2018-08-23 18:27 UTC
