### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by VeraShevelyova** [john-doherty/selenium-cucumber-js#33] opened 2017-08-16 17:25 UTC
I have Windows 7 and after I cloned application and run **npm install** and then node index.js I got following error
selenium-cucumber-js\node_modules\selenium-web
driver\index.js:115
  static createSession(...args) {}
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Vera\Desktop\SlotMachine\selenium-cucumber-j
s\runtime\world.js:13:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by john-doherty** [comment] 2017-08-24 15:08
Hey @VeraShevelyova, I don't have access to a windows machine to test this... Anyone else?

**Comment by larryg01** [comment] 2017-09-22 10:51
@VeraShevelyova, did you manage to get this working? if not can you tell me exactly what is it you are passing after index.js please

**Comment by john-doherty** [comment] 2017-09-22 12:56
Thanks @larryg01, appreciate the help. I suspect it's a path issue

**Comment by john-doherty** [comment] 2017-12-18 17:20
Any progress on this?

**Comment by larryg01** [comment] 2017-12-18 17:29
The user never got back to me on it so i completely forgot all about it.
Do you think it still needs looking into, if so i will do it over the wknd, not a prob

**Comment by john-doherty** [comment] 2017-12-18 17:30
No, it might have been related to one of the many issues that have since been resolved. I'll close it for now. @VeraShevelyova please reopen if you are able to reproduce with the latest version.

**Closed by john-doherty** 2017-12-18 17:30 UTC
Labels: help wanted
